# Travis CI configuration file
# http://about.travis-ci.org/docs/

dist: xenial

language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

env:
  - TEST_PARAM="--unit -v"
  - TEST_PARAM="--integ -v"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev libssl-dev zlib1g-dev python-tox python-dev python3-dev wget
  - cd ~/
  - wget https://dist.torproject.org/tor-0.4.0.5.tar.gz
  - tar zxf tor-0.4.0.5.tar.gz && cd tor-0.4.0.5
  - ./configure && make

cache:
  directories:
  - .autoconf
  - $HOME/.tor-0.4.0.5

# Dependencies installation commands
install:
  - cd $TRAVIS_BUILD_DIR
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install wrapt_timeout_decorator

# Tests running commands
script:
  - TOR_BINARY=./tor-0.4.0.5/src/app/tor python run_tests.py -v $TEST_PARAM --tor ./tor-0.4.0.5/src/app/tor

notifications:
  email: false

after_script:
  # List installed packages along with their versions.
  - "pip list"

sudo: false

git:
  depth: 300
